// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicPaper2Button,
  DefaultPaper2ButtonProps
} from "./plasmic/john_minelli_page/PlasmicPaper2Button";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface Paper2ButtonProps extends Omit<DefaultPaper2ButtonProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultPaper2ButtonProps altogether and have
// total control over the props for your component.
export interface Paper2ButtonProps extends DefaultPaper2ButtonProps {}

function Paper2Button_(props: Paper2ButtonProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicPaper2Button to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicPaper2Button are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all Paper2ButtonProps here, but feel free
  // to do whatever works for you.

  return <PlasmicPaper2Button root={{ ref }} {...props} />;
}

const Paper2Button = React.forwardRef(Paper2Button_);
export default Paper2Button;
